version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install."
  build:
    commands:
      - echo Build started on `date`
      - cd lambda      
      - python ../zip.py ../Compare_CurrentSP_Intent.zip compare_currentsp_intent.py ihbot_config.py ihbot_helpers.py ihbot_userexits.py
      - python ../zip.py ../Compare_DayGain_Intent.zip compare_daygain_intent.py ihbot_config.py ihbot_helpers.py ihbot_userexits.py
      - python ../zip.py ../Refresh_Intent.zip refresh_intent.py ihbot_config.py ihbot_helpers.py ihbot_userexits.py
      - python ../zip.py ../Compare_LatestValue_Intent.zip compare_latestvalue_intent.py ihbot_config.py ihbot_helpers.py ihbot_userexits.py
      - python ../zip.py ../Compare_OpeningPrices_Intent.zip compare_openingprices_intent.py ihbot_config.py ihbot_helpers.py ihbot_userexits.py
      - cd ..
      - ls -l *.zip
      - bash delete.sh
      - bash build-db.sh
      - bash build-bot.sh
  post_build:
    commands:
      - echo Build completed on `date`

